package com.tocletoque.thebreedinglab.common

import com.tocletoque.thebreedinglab.model.Dog
import com.tocletoque.thebreedinglab.model.GameTime
import com.tocletoque.thebreedinglab.model.Reputation
import com.tocletoque.thebreedinglab.model.Sex
import java.time.LocalDate

object Constant {

    val gameTime = GameTime()

    val dogList = listOf(
        Dog(
            "Daisy",
            Sex.Female,
            LocalDate.of(2024, 6, 5),
            "Bb",
            "ee",
            "DD",
            "Tt",
            "Nm",
            "NN",
            "Nm",
            "NN",
            "Nm",
            1050,
            "friendly",
            "high",
            "medium",
            false,
            unlockedAt = Reputation.NoviceBreeder
        ),
        Dog(
            "Prince",
            Sex.Male,
            LocalDate.of(2017, 9, 12),
            "bb",
            "ee",
            "DD",
            "tt",
            "mm",
            "mm",
            "mm",
            "mm",
            "mm",
            900,
            "reactive",
            "low",
            "low",
            false,
            unlockedAt = Reputation.NoviceBreeder
        ),
        Dog(
            "Bea",
            Sex.Female,
            LocalDate.of(2023, 7, 24),
            "Bb",
            "EE",
            "DD",
            "Tt",
            "NN",
            "NN",
            "NN",
            "NN",
            "Nm",
            1350,
            "friendly",
            "medium",
            "medium",
            false,
            unlockedAt = Reputation.AmateurBreeder
        ),
        Dog(
            "Ollie",
            Sex.Male,
            LocalDate.of(2019, 9, 9),
            "Bb",
            "Ee",
            "DD",
            "TT",
            "Nm",
            "Nm",
            "Nm",
            "NN",
            "NN",
            1000,
            "shy",
            "low",
            "low",
            false,
            unlockedAt = Reputation.AmateurBreeder
        ),
        Dog(
            "Luna",
            Sex.Female,
            LocalDate.of(2022, 10, 1),
            "bb",
            "EE",
            "DD",
            "Tt",
            "NN",
            "NN",
            "NN",
            "NN",
            "NN",
            1750,
            "friendly",
            "high",
            "high",
            false,
            unlockedAt = Reputation.ExperiencedBreeder
        ),
        Dog(
            "Samson",
            Sex.Male,
            LocalDate.of(2023, 1, 18),
            "BB",
            "Ee",
            "DD",
            "tt",
            "NN",
            "NN",
            "Nm",
            "NN",
            "NN",
            1600,
            "reactive",
            "medium",
            "high",
            false,
            unlockedAt = Reputation.ExperiencedBreeder
        ),
        Dog(
            "Ocean",
            Sex.Female,
            LocalDate.of(2023, 8, 21),
            "bb",
            "Ee",
            "dd",
            "TT",
            "Nm",
            "NN",
            "NN",
            "Nm",
            "mm",
            2000,
            "friendly",
            "medium",
            "high",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Forest",
            Sex.Male,
            LocalDate.of(2021, 8, 1),
            "bb",
            "EE",
            "dd",
            "Tt",
            "NN",
            "NN",
            "Nm",
            "Nm",
            "Nm",
            2000,
            "shy",
            "high",
            "medium",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Darcy",
            Sex.Female,
            LocalDate.of(2022, 8, 15),
            "BB",
            "ee",
            "dd",
            "tt",
            "NN",
            "Nm",
            "mm",
            "NN",
            "Nm",
            2000,
            "reactive",
            "medium",
            "medium",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Dane",
            Sex.Male,
            LocalDate.of(2021, 6, 10),
            "Bb",
            "EE",
            "dd",
            "Tt",
            "mm",
            "NN",
            "Nm",
            "mm",
            "NN",
            2000,
            "friendly",
            "low",
            "high",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Bella",
            Sex.Female,
            LocalDate.of(2023, 8, 3),
            "Bb",
            "Ee",
            "dd",
            "tt",
            "NN",
            "NN",
            "NN",
            "NN",
            "Nm",
            2000,
            "shy",
            "medium",
            "low",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Watson",
            Sex.Male,
            LocalDate.of(2022, 8, 27),
            "BB",
            "EE",
            "dd",
            "Tt",
            "NN",
            "Nm",
            "NN",
            "NN",
            "NN",
            2000,
            "friendly",
            "high",
            "high",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Alice",
            Sex.Female,
            LocalDate.of(2023, 8, 14),
            "BB",
            "Ee",
            "Dd",
            "TT",
            "NN",
            "NN",
            "mm",
            "NN",
            "NN",
            2000,
            "reactive",
            "medium",
            "medium",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Rex",
            Sex.Male,
            LocalDate.of(2023, 8, 19),
            "bb",
            "ee",
            "DD",
            "tt",
            "Nm",
            "NN",
            "NN",
            "Nm",
            "NN",
            2000,
            "friendly",
            "medium",
            "medium",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Tara",
            Sex.Female,
            LocalDate.of(2021, 8, 30),
            "bb",
            "EE",
            "dd",
            "tt",
            "NN",
            "NN",
            "NN",
            "NN",
            "NN",
            2000,
            "shy",
            "low",
            "low",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
        Dog(
            "Copper",
            Sex.Male,
            LocalDate.of(2023, 7, 25),
            "BB",
            "ee",
            "dd",
            "tt",
            "NN",
            "NN",
            "NN",
            "NN",
            "NN",
            2000,
            "friendly",
            "high",
            "medium",
            true,
            unlockedAt = Reputation.ProfessionalBreeder
        ),
    )

    const val FOOD_COST_PER_DOG = 50
    const val PUPPY_TRAINING_COST_PER_PUPPY = 40
    const val GROOMING_COST_PER_DOG = 30

}